### ISSUE TITLE
Automated build of the doc is broken

### ISSUE THREAD

**Issue by btravouillon** [mila-iqia/mila-docs#203]
Tests are failing:

- https://github.com/mila-iqia/mila-docs/actions/runs/5533095606/jobs/10096241602
- https://github.com/mila-iqia/mila-docs/actions/runs/5533077130/jobs/10096070001

The error is:
> Usage:   
>    pip install [options] <requirement specifier> [package-index-options] ...
>    pip install [options] -r <requirements file> [package-index-options] ...
>    pip install [options] [-e] <vcs project url> ...
>    pip install [options] [-e] <local project path> ...
>    pip install [options] <archive url/path> ...
>  
>  no such option: --break-system-packages
>  Running Sphinx v6.2.1
>  
>  Configuration error:
>  There is a programmable error in your configuration file:
>  
>  Traceback (most recent call last):
>    File "/usr/local/lib/python3.9/site-packages/sphinx/config.py", line 354, in eval_config_file
>      exec(code, namespace)  # NoQA: S102
>    File "/src/docs/conf.py", line 9, in <module>
>      import sphinx_theme
>  ModuleNotFoundError: No module named 'sphinx_theme'

The GH ACtion is using container https://hub.docker.com/r/btdi/btd that was updated yesterday. 

The issue might be related to [this change](https://github.com/buildthedocs/btd/commit/68bcd4725cbd383047ec8520562fd5d00db376fa), however a [fix was pushed a couple of hours later](https://github.com/buildthedocs/btd/commit/87121253d3eb05b252853a7e8fa8550b91af303e). Is it possible that the container is not up-to-date?

**Comment by btravouillon** [comment]
I filed https://github.com/buildthedocs/btd/issues/11 upstream.

**Comment by satyaog** [comment]
Temporary fixed by #204
